[package]
name = "video_enhancer"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.49", features = ["derive"] }
indicatif = "0.18.0"
regex = "1.12.2"
thiserror = "2.0.17"
which = "8.0.0"
dialoguer = "0.11"
